
import PptxGenJS from 'pptxgenjs';
import { DataItem, ReportChart } from '../types';

export const exportToPPT = async (
  data: DataItem[], 
  reportContent: string, 
  charts: ReportChart[],
  filename: string = "BroExcel_Presentation"
) => {
  try {
    const pres = new PptxGenJS();
    
    // Theme Colors
    pres.theme = { headFontFace: "Arial", bodyFontFace: "Arial" };

    // 1. Title Slide
    const slide1 = pres.addSlide();
    slide1.background = { color: "F1F5F9" };
    slide1.addText("Operations Analysis Report", { 
        x: 1, y: 2, w: '80%', fontSize: 36, bold: true, color: "1E293B", align: "center" 
    });
    slide1.addText(`Generated by BroExcel AI | ${new Date().toLocaleDateString()}`, { 
        x: 1, y: 3.5, w: '80%', fontSize: 14, color: "64748B", align: "center" 
    });

    // 2. Executive Summary (Extracted from Report)
    const summaryRegex = /## 1. Executive Summary([\s\S]*?)##/i;
    const summaryMatch = reportContent.match(summaryRegex);
    const summaryText = summaryMatch ? summaryMatch[1].trim() : "Summary not available.";

    const slide2 = pres.addSlide();
    slide2.addText("Executive Summary", { x: 0.5, y: 0.5, fontSize: 24, bold: true, color: "334155" });
    slide2.addShape(pres.ShapeType.rect, { x: 0.5, y: 1.2, w: 9, h: 0.05, fill: "3B82F6" });
    slide2.addText(summaryText, { x: 0.5, y: 1.5, w: 9, fontSize: 14, color: "475569", breakLine: true });

    // 3. Key Data (Table)
    const slide3 = pres.addSlide();
    slide3.addText("Data Overview", { x: 0.5, y: 0.5, fontSize: 24, bold: true, color: "334155" });
    
    if (data.length > 0) {
        // Take first 6 columns and top 10 rows
        const keys = Object.keys(data[0]).slice(0, 6);
        const tableRows = [];
        
        // Header
        tableRows.push(keys.map(k => ({ text: k, options: { bold: true, fill: "E2E8F0", color: "1E293B" } })));
        
        // Body
        data.slice(0, 10).forEach(row => {
            tableRows.push(keys.map(k => row[k]?.toString() || ""));
        });

        slide3.addTable(tableRows, { x: 0.5, y: 1.5, w: 9, fontSize: 10, border: { pt: 1, color: "CBD5E1" } });
    }

    // 4. Recommendations (Extracted)
    const recRegex = /## 5. Recommendations([\s\S]*?)##/i;
    const recMatch = reportContent.match(recRegex) || reportContent.match(/## 5. Recommendations([\s\S]*?)$/i);
    const recText = recMatch ? recMatch[1].trim() : "See full report for details.";

    const slide4 = pres.addSlide();
    slide4.addText("Strategic Recommendations", { x: 0.5, y: 0.5, fontSize: 24, bold: true, color: "334155" });
    slide4.addShape(pres.ShapeType.rect, { x: 0.5, y: 1.2, w: 9, h: 0.05, fill: "10B981" });
    slide4.addText(recText, { x: 0.5, y: 1.5, w: 9, fontSize: 14, color: "475569", breakLine: true });

    // 5. Conclusion
    const slide5 = pres.addSlide();
    slide5.background = { color: "1E293B" };
    slide5.addText("Thank You", { x: 0, y: 2.5, w: '100%', fontSize: 48, bold: true, color: "FFFFFF", align: "center" });

    // Save
    await pres.writeFile({ fileName: `${filename}.pptx` });
    return true;
  } catch (error) {
    console.error("PPT Gen Error", error);
    return false;
  }
};
